Class {
	#name : 'TonelShadowMockK',
	#superclass : 'Object',
	#instVars : [
		'instVar1'
	],
	#classVars : [
		'ClassVar1'
	],
	#pools : [
		'CldtConstants'
	],
	#classInstVars : [
		'classInstVar1'
	],
	#category : 'TonelWriterTests-TonelWriterTestShadowSubSubSubApp'
}

{
	#category : 'Not categorized'
}
TonelShadowMockK >> shadowSubMethodForTest [

	^'Shadow sub method for testing TonelWriter'
]
