Class {
	#name : 'TonelMockPoolDefinitionClass',
	#superclass : 'Object',
	#category : 'TonelWriterTests'
}

{ #category : 'Not categorized' }
TonelMockPoolDefinitionClass class >> _PRAGMA_TonelMockPool [

	"%%PRAGMA DECLARE
	(name: TonelMockPool isPool: true isConstant: true)
	(pool: TonelMockPool declarations: (
		(name: TMMx01 isConstant: true valueExpression: '''Sample Pool Element''')
	))"

]
